apiVersion: v1
kind: Service
metadata:
  name: batchops-dashboard-service

spec:
  type: NodePort

  selector:
    app: batchops-dashboard

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001